package com.nxg.openclawproot

import java.io.File

object GatewayRuntimeFiles {
    fun ensure(filesDir: String) {
        val rootfsDir = File(filesDir, "rootfs/ubuntu")
        val openClawDir = File(rootfsDir, "root/.openclaw")
        openClawDir.mkdirs()

        // Cache directories
        File(rootfsDir, "root/.cache/node/compile_cache").mkdirs()
        File(rootfsDir, "root/.cache/npm").mkdirs()
        File(rootfsDir, "tmp/npm-cache").mkdirs()

        writeStartGatewayScript(File(openClawDir, "start-gateway.sh"))
        writeMinimalConfig(File(openClawDir, "openclaw.json"))
    }

    /**
     * Generate the start-gateway.sh script:
     * - Cache directories
     * - Validate node and openclaw binaries
     * - Repair config with openclaw doctor --fix
     * - PID file
     * - Launch openclaw gateway
     */
    private fun writeStartGatewayScript(startScript: File) {
        startScript.writeText("""#!/data/data/com.nxg.openclawproot/files/rootfs/ubuntu/bin/bash
# OpenClaw runtime gateway launcher. Generated by the Android service.
# NO set -e — explicit error handling, the script must always reach
# the final exec openclaw gateway command.

exec 2>&1

# ── Log helper ─────────────────────────────────────────────────────────
log() {
  echo "[gateway] ${'$'}@"
}

log "starting"

# ── Environment ───────────────────────────────────────────────────────
export NODE_OPTIONS="${GatewayRuntimePolicy.nodeOptions()}"
export NODE_COMPILE_CACHE="/root/.cache/node/compile_cache"
export XDG_CACHE_HOME="/root/.cache"
export npm_config_cache="/root/.cache/npm"
export OPENCLAW_NO_RESPAWN=1
export OPENCLAW_NO_WATCHDOG=1
export UV_THREADPOOL_SIZE=4
export UV_USE_IO_URING=0
export CHOKIDAR_USEPOLLING=false
export CHOKIDAR_INTERVAL=2000

# ── Required dirs ──────────────────────────────────────────────────────
mkdir -p "${'$'}NODE_COMPILE_CACHE" "${'$'}XDG_CACHE_HOME" "${'$'}npm_config_cache" /tmp/npm-cache /root/.openclaw 2>/dev/null || true
log "dirs ready"

# ── Validate node ──────────────────────────────────────────────────────
if command -v node >/dev/null 2>&1; then
  NODE_VER=$(node -v 2>/dev/null || echo "unknown")
  log "checking node ${'$'}NODE_VER"
else
  log "WARN: node not in PATH, trying direct path"
  if [ -x /usr/local/bin/node ]; then
    export PATH="/usr/local/bin:${'$'}PATH"
    NODE_VER=$(/usr/local/bin/node -v 2>/dev/null || echo "unknown")
    log "node ${'$'}NODE_VER (direct)"
  else
    log "CRITICAL: node binary not found"
    exit 1
  fi
fi

# ── Validate openclaw ──────────────────────────────────────────────────
if command -v openclaw >/dev/null 2>&1; then
  OCLAW_VER=$(openclaw --version 2>/dev/null || echo "unknown")
  log "checking openclaw ${'$'}OCLAW_VER"
else
  log "WARN: openclaw not in PATH, trying direct path"
  if [ -x /usr/local/bin/openclaw ]; then
    export PATH="/usr/local/bin:${'$'}PATH"
    OCLAW_VER=$(/usr/local/bin/openclaw --version 2>/dev/null || echo "unknown")
    log "openclaw ${'$'}OCLAW_VER (direct)"
  else
    log "CRITICAL: openclaw binary not found"
    exit 1
  fi
fi

log "validations passed"

# ── Repair config ──────────────────────────────────────────────────────
# OpenClaw 2026.5.7 rejects unknown keys (e.g. "plugins" inside "gateway").
# Run doctor --fix to repair any config issues before launching.
openclaw doctor --fix 2>/dev/null || true
log "config repaired"

# ── PID file ───────────────────────────────────────────────────────────
echo "${'$'}${'$'}" > /root/.openclaw/gateway.pid 2>/dev/null || true

# ── Launch ─────────────────────────────────────────────────────────────
log "launching"
exec openclaw gateway --no-color --no-emoji
""".trimIndent())
        startScript.setExecutable(true, false)
    }

    /**
     * Write minimal valid openclaw.json if it does not exist yet.
     * Only writes if the file does not exist, to avoid overwriting user config.
     */
    private fun writeMinimalConfig(configFile: File) {
        if (configFile.exists()) return // don't overwrite existing config
        configFile.writeText("""{
  "gateway": {
    "mode": "local"
  }
}
""".trimIndent())
    }
}
