package com.nxg.openclawproot

import java.io.File

object GatewayRuntimeFiles {
    fun ensure(filesDir: String) {
        val rootfsDir = File(filesDir, "rootfs/ubuntu")
        val openClawDir = File(rootfsDir, "root/.openclaw")
        openClawDir.mkdirs()

        // Cache directories
        File(rootfsDir, "root/.cache/node/compile_cache").mkdirs()
        File(rootfsDir, "root/.cache/npm").mkdirs()
        File(rootfsDir, "tmp/npm-cache").mkdirs()

        writeStartGatewayScript(File(openClawDir, "start-gateway.sh"))
        writeOpenClawConfigPatch(File(openClawDir, "openclaw.json"))
    }

    /**
     * Generate the start-gateway.sh script with:
     * - Config repair before launch
     * - Heavy plugins disabled (browser, phone-control, talk-voice)
     * - Light plugins enabled (telegram, memory-core, device-pair, file-transfer)
     * - Cache directories
     * - PID file
     */
    private fun writeStartGatewayScript(startScript: File) {
        startScript.writeText("""#!/data/data/com.nxg.openclawproot/files/rootfs/ubuntu/bin/bash
# OpenClaw runtime gateway launcher. Generated by the Android service.

set -e

# ── Environment ───────────────────────────────────────────────────────
export NODE_OPTIONS="${GatewayRuntimePolicy.nodeOptions()}"
export NODE_COMPILE_CACHE="/root/.cache/node/compile_cache"
export XDG_CACHE_HOME="/root/.cache"
export npm_config_cache="/root/.cache/npm"
export OPENCLAW_NO_RESPAWN=1
export OPENCLAW_NO_WATCHDOG=1
export UV_THREADPOOL_SIZE=4
export UV_USE_IO_URING=0
export CHOKIDAR_USEPOLLING=false
export CHOKIDAR_INTERVAL=2000

# ── Cache dirs ─────────────────────────────────────────────────────────
mkdir -p "${NODE_COMPILE_CACHE}" "${XDG_CACHE_HOME}" "${npm_config_cache}" /tmp/npm-cache 2>/dev/null

# ── Config repair ──────────────────────────────────────────────────────
CONFIG_FILE="/root/.openclaw/openclaw.json"
if [ -f "$CONFIG_FILE" ]; then
  # Disable heavy plugins by default (user can re-enable later)
  for plugin in browser phone-control talk-voice; do
    # Use a temporary marker to avoid repeated sed calls
    if grep -q "\"$plugin\"" "$CONFIG_FILE" 2>/dev/null; then
      # Only patch if the plugin exists and isn't already disabled
      if ! grep -q "\"$plugin\":\s*false" "$CONFIG_FILE" 2>/dev/null; then
        sed -i "s/\"$plugin\"\s*:\s*true/\"$plugin\": false/g" "$CONFIG_FILE" 2>/dev/null || true
      fi
    fi
  done
fi

# ── PID file ───────────────────────────────────────────────────────────
echo "$$" > /root/.openclaw/gateway.pid 2>/dev/null || true

# ── Launch ─────────────────────────────────────────────────────────────
exec openclaw gateway --no-color --no-emoji 2>&1
""".trimIndent())
        startScript.setExecutable(true, false)
    }

    /**
     * Pre-configure openclaw.json with safe defaults for plugins.
     * Only writes if the file does not exist yet.
     */
    private fun writeOpenClawConfigPatch(configFile: File) {
        if (configFile.exists()) return // don't overwrite existing config
        configFile.writeText("""{
  "plugins": {
    "telegram": true,
    "memory-core": true,
    "device-pair": true,
    "file-transfer": true,
    "browser": false,
    "phone-control": false,
    "talk-voice": false
  }
}
""".trimIndent())
    }
}
