package com.nxg.openclawproot

import java.io.File

object GatewayRuntimeFiles {
    fun ensure(filesDir: String) {
        val rootfsDir = File(filesDir, "rootfs/ubuntu")
        val openClawDir = File(rootfsDir, "root/.openclaw")
        openClawDir.mkdirs()

        File(rootfsDir, "root/.cache/node/compile_cache").mkdirs()
        File(rootfsDir, "root/.cache/npm").mkdirs()
        File(rootfsDir, "tmp/npm-cache").mkdirs()

        writeStartGatewayScript(File(openClawDir, "start-gateway.sh"))
    }

    private fun writeStartGatewayScript(startScript: File) {
        startScript.writeText("""#!/data/data/com.nxg.openclawproot/files/rootfs/ubuntu/bin/bash
# OpenClaw runtime gateway launcher. Generated by the Android service
# before gateway start so existing installations receive current tuning.

export NODE_OPTIONS="${GatewayRuntimePolicy.nodeOptions()}"

export NODE_COMPILE_CACHE="/root/.cache/node/compile_cache"
export XDG_CACHE_HOME="/root/.cache"
export npm_config_cache="/root/.cache/npm"
mkdir -p "${'$'}NODE_COMPILE_CACHE" "${'$'}XDG_CACHE_HOME" "${'$'}npm_config_cache" /tmp/npm-cache 2>/dev/null

export OPENCLAW_NO_RESPAWN=1
export OPENCLAW_NO_WATCHDOG=1
export UV_THREADPOOL_SIZE=4
export UV_USE_IO_URING=0
export CHOKIDAR_USEPOLLING=false
export CHOKIDAR_INTERVAL=2000

exec openclaw gateway --no-color --no-emoji 2>&1
""".trimIndent())
        startScript.setExecutable(true, false)
    }
}
