name: flutter_blue_plus_android
description: Android implementation of the flutter_blue_plus plugin.
version: 9.0.0
homepage: https://github.com/chipweinberger/flutter_blue_plus

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"


