#!/data/data/com.nxg.openclawproot/files/rootfs/ubuntu/bin/bash
# OpenClaw runtime gateway launcher. Generated by the Android service.
# NO set -e — explicit error handling, the script must always reach
# the final exec openclaw gateway command.

exec 2>&1

# ── Log helper ─────────────────────────────────────────────────────────
log() {
  echo "[gateway] $@"
}

log "starting"

# ── Environment ───────────────────────────────────────────────────────
export NODE_OPTIONS="--require /root/.openclaw/bionic-bypass.js --max-old-space-size=384 --optimize-for-size --max-semi-space-size=32"
export NODE_COMPILE_CACHE="/root/.cache/node/compile_cache"
export XDG_CACHE_HOME="/root/.cache"
export npm_config_cache="/root/.cache/npm"
export OPENCLAW_NO_RESPAWN=1
export OPENCLAW_NO_WATCHDOG=1
export UV_THREADPOOL_SIZE=4
export UV_USE_IO_URING=0
export CHOKIDAR_USEPOLLING=false
export CHOKIDAR_INTERVAL=2000

# ── Required dirs ──────────────────────────────────────────────────────
mkdir -p "$NODE_COMPILE_CACHE" "$XDG_CACHE_HOME" "$npm_config_cache" /tmp/npm-cache /root/.openclaw 2>/dev/null || true
log "dirs ready"

# ── Validate node ──────────────────────────────────────────────────────
if command -v node >/dev/null 2>&1; then
  NODE_VER=$(node -v 2>/dev/null || echo "unknown")
  log "checking node $NODE_VER"
else
  log "WARN: node not in PATH, trying direct path"
  if [ -x /usr/local/bin/node ]; then
    export PATH="/usr/local/bin:$PATH"
    NODE_VER=$(/usr/local/bin/node -v 2>/dev/null || echo "unknown")
    log "node $NODE_VER (direct)"
  else
    log "CRITICAL: node binary not found"
    exit 1
  fi
fi

# ── Validate openclaw ──────────────────────────────────────────────────
if command -v openclaw >/dev/null 2>&1; then
  OCLAW_VER=$(openclaw --version 2>/dev/null || echo "unknown")
  log "checking openclaw $OCLAW_VER"
else
  log "WARN: openclaw not in PATH, trying direct path"
  if [ -x /usr/local/bin/openclaw ]; then
    export PATH="/usr/local/bin:$PATH"
    OCLAW_VER=$(/usr/local/bin/openclaw --version 2>/dev/null || echo "unknown")
    log "openclaw $OCLAW_VER (direct)"
  else
    log "CRITICAL: openclaw binary not found"
    exit 1
  fi
fi

log "validations passed"

# ── Disable heavy plugins ──────────────────────────────────────────────
# Browser/phone/talk-voice plugins can crash in proot (no Chrome, no telephony).
CONFIG_FILE="/root/.openclaw/openclaw.json"
if [ -f "$CONFIG_FILE" ]; then
  sed -i 's/"browser":[[:space:]]*true/"browser": false/g' "$CONFIG_FILE" 2>/dev/null || true
  sed -i 's/"phone-control":[[:space:]]*true/"phone-control": false/g' "$CONFIG_FILE" 2>/dev/null || true
  sed -i 's/"talk-voice":[[:space:]]*true/"talk-voice": false/g' "$CONFIG_FILE" 2>/dev/null || true
fi
log "plugins configured"

# ── PID file ───────────────────────────────────────────────────────────
echo "$$" > /root/.openclaw/gateway.pid 2>/dev/null || true

# ── Launch ─────────────────────────────────────────────────────────────
log "launching"
exec openclaw gateway --no-color --no-emoji
