include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "local_plugins_backup_built_in_kotlin/**"
    - "**/example/**"
    - "**/integration_test/**"

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: false
